swagger: '2.0'
info:
  version: 0.0.11
  title: Quas
host: 'localhost:2302'
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /books:
    x-swagger-router-controller: books
    get:
      tags:
        - Books
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HelloWorldResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - Books
      description: Returns 'Hello' to the caller
      operationId: hello2
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HelloWorldResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /edits:
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      operationId: hellos
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HelloWorldResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  HelloWorldResponse:
    required:
      - message
      - name
    properties:
      message:
        type: string
      name:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string